from dramapp.models import Region, Distillery, Whisky

rIslay = Region(region = 'Islay')
rIslay.save()
rSpey = Region(region = 'Speyside',)
rSpey.save()
rHigh = Region(region = 'Highland',)
rHigh.save()
rLow = Region(region = 'Lowland',)
rLow.save()
rIsland = Region(region = 'Island',)
rIsland.save()
rCamp = Region(region = 'Campbeltown',)
rCamp.save()

d1 = Distillery(id = 001, name = 'Laphroaig', region = rIslay, latitude = '55.62989', longitude = '-6.15202', images = 'test', website = 'http://www.laphroaig.com/', tourevents = 'test',)
d1.save()
d2 = Distillery(id = 002, name = 'Ardbeg', region = rIslay, latitude = '55.6404', longitude = '6.1087', images = 'test', website = 'http://www.ardbeg.com/', tourevents = 'test',)
d2.save()
d3 = Distillery(id = 003, name = 'Old Pulteney', region = rHigh, latitude = '58.4491', longitude = '3.1701', images = 'test', website = 'http://www.oldpulteney.com/', tourevents = 'test',)
d3.save()
d4 = Distillery(id = 004, name = 'Edradour', region = rHigh, latitude = '56.7017', longitude = '3.7008', images = 'test', website = 'http://www.edradour.com/', tourevents = 'test',)
d4.save()
d5 =Distillery(id = 005, name= 'Balblair', region = rHigh, latitude = '57.8398', longitude = ' 4.1808', images = 'test', website = 'http://www.balblair.com/', tourevents = 'test',)
d5.save()
d6 = Distillery(id = 006, name = 'Glenfiddich', region = rSpey, latitude = '57.27', longitude = '3.7', images = 'test', website = 'http://www.glenfiddich.com/', tourevents = 'test',)
d6.save()
d7 = Distillery(id = 007, name = 'Glenlivet', region = rSpey, latitude = '57.341056', longitude = '3.334715', images = 'test', website = 'http://www.theglenlivet.com/', tourevents = 'test',)
d7.save()
d8 = Distillery(id = 008, name = 'Auchentoshan', region = rLow, latitude = '55.51', longitude = '2.55', images = 'test', website = 'http://www.auchentoshan.com/', tourevents = 'test',)
d8.save()
d9 = Distillery(id = 009, name = 'Glenkinchie', region = rLow, latitude = '55.89021', longitude = '-2.892862', images = 'test', website = 'http://www.discovering-distilleries.com/agecheck.php?redirect=/glenkinchie/index.php', tourevents = 'test',)
d9.save()
d10 = Distillery(id = 010, name = 'Highland Park', region = rIsland, latitude = '58.59', longitude = '2.55', images = 'test', website = 'http://www.highlandpark.co.uk/', tourevents = 'test',)
d10.save()

w1 = Whisky(id = 0010, name = 'Laphroaig', age = '10', whiskytype = 'Single Malt', distillery = d1, region = rIslay, rating = 'test', tastingnotes = 'Full bodied, Peaty, Smokey', barrelType = 'wood', image = 'test', website = 'http://www.laphroaig.com/whiskies/10yo.aspx', price = '37.50',)
w1.save()
w2 = Whisky(id = 0020, name = 'Ardbeg', age = '10', whiskytype = 'Single Malt', distillery = d2, region = rIslay, rating = 'test', tastingnotes = 'Peaty, smokey', barrelType = 'test', image = 'test', website = 'http://www.ardbeg.com/ardbeg/the-ardbeg-range', price = '38.70',)
w2.save()
w3 = Whisky(id = 0030, name = 'Old Pulteney', age = '12', whiskytype = 'Single Malt', distillery = d3, region = rHigh, rating = 'test', tastingnotes = 'Fruity, Spice', barrelType = 'test', image = 'test', website = 'http://www.oldpulteney.com/old-pulteney-whisky/12-year-old-single-malt/', price = '30.99',)
w3.save()
w4 = Whisky(id = 0031, name = 'Old Pulteney', age = '17', whiskytype = 'Single Malt', distillery = d3, region = rHigh, rating = 'test', tastingnotes = 'Complex, wood, fruit, creamy', barrelType = 'test', image = 'test', website = 'http://www.oldpulteney.com/old-pulteney-whisky/17-year-old-single-malt/', price = '52.30',)
w4.save()
w5 = Whisky(id = 0032, name = 'Old Pulteney', age = '21', whiskytype = 'Single Malt', distillery = d3, region = rHigh, rating = 'test', tastingnotes = 'Light, Fruity, Honey, Vanilla', barrelType = 'test', image = 'test', website = 'http://www.oldpulteney.com/old-pulteney-whisky/21-year-old-single-malt/', price = '80.70',)
w5.save()
w6 = Whisky(id = 0040, name = 'Auchentoshan', age = '12', whiskytype = 'Single Malt', distillery = d8, region = rLow, rating = 'test', tastingnotes = 'Smooth, nutty, fruity', barrelType = 'test', image = 'test', website = 'http://www.auchentoshan.com/products/our-range.aspx', price = '30.50',)
w6.save()
w7 = Whisky(id = 0050, name = 'Balblair', age = '10', whiskytype = 'Single Malt', distillery = d5, region = rHigh, rating = 'test', tastingnotes = 'Full bodied, fruity', barrelType = 'test', image = 'test', website = 'http://www.balblair.com/exclusive-vintages/', price = '42.00',)
w7.save()
w8 = Whisky(id = 0060, name = 'Edradour', age = '10', whiskytype = 'Single Malt', distillery = d4, region = rHigh, rating = 'test', tastingnotes = 'Fruity', barrelType = 'test', image = 'test', website = 'test', price = '32.50',)
w8.save()
w9 = Whisky(id = 0070, name = 'Glenfiddich', age = '12', whiskytype = 'Single Malt', distillery = d6, region = rSpey, rating = 'test', tastingnotes = 'Fruity', barrelType = 'test', image = 'test', website = 'http://www.glenfiddich.com/', price = '34.75',)
w9.save()
w10 = Whisky(id = 0080, name = 'Glenkinchie', age = '12', whiskytype = 'Single Malt', distillery = d9, region = rLow, rating = 'test', tastingnotes = 'Smooth, sweet', barrelType = 'test', image = 'test', website = 'test', price = '34.00',)
w10.save()
w11 = Whisky(id = 0090, name = 'Glenlivet', age = '12', whiskytype = 'Single Malt', distillery = d7, region = rSpey, rating = 'test', tastingnotes = 'Light, fruity', barrelType = 'test', image = 'test', website = 'test', price = '34.00',)
w11.save()
w12 = Whisky(id = 0100, name = 'Highland Park', age = '12', whiskytype = 'Single Malt', distillery = d10, region = rIslay, rating = 'test', tastingnotes = 'Light smoke, honey, fruit', barrelType = 'wood', image = 'test', website = 'test', price = '30.00',)
w12.save()

